### ISSUE TITLE
Unused account (want the name)

### ISSUE THREAD

**Issue by james-darkfox** [pupperirl/ripthis#1]
Hello Ambiance.

I have a project named Ambiance and it would seem that you are not using this account. Could you please delete it or claim another name?

Thanks in advance.

**Comment by VsyachePuz** [comment]
Yes, we are internationally distributed supporters of darkfox, demand the transfer of this unused name to him.

**Comment by pupperirl** [comment]
Sorry it took so long but I've changed the name and it should be available to you now.

**Comment by james-darkfox** [comment]
Thanks!

**Comment by james-darkfox** [comment]
Thanks!
